[application]
name = "reality"
default_platform = "web"

[web.app]
title = "reality"
base_path = "/"

[web.resource]
style = ["/assets/main.css"]
script = []

[web.resource.dev]
script = []

[web.wasm_opt]
level = "z"